import { COLORS } from "@/constants/theme";
import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.background,
    paddingBottom: 30,
    flex: 1,
    flexDirection: "column",
  },
  header: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 10,
    justifyContent: "flex-start",
    alignItems: "center",

    textAlign: "center",
  },
  headerTitle: {
    fontSize: 36,
    color: COLORS.textPrimary,
    marginBottom: -3,
    marginTop: 0,
    fontFamily: "PoppinsBold",
    paddingTop: 30,
    width: 280,
    textAlign: "center",
    paddingHorizontal: 20,
  },
  headerSubtitle: {
    fontSize: 15,
    color: COLORS.textSecondary,
    fontFamily: "OpenSansRegular",
  },
  gradientBar: {
    height: 3,
    borderRadius: 2,
    marginBottom: 12,
  },
  infoSection: {
    paddingHorizontal: 8,
  },
  infoTitle: {
    alignSelf: "center",
    marginTop: 15,
    fontSize: 32,
    fontFamily: "PoppinsBold",
    color: COLORS.textPrimary,
    marginBottom: -5,
  },
  infoText: {
    alignSelf: "center",
    color: COLORS.textSecondary,
    fontFamily: "InterMedium",
    fontSize: 18,
  },
  infoHeader: {
    height: 180,
    width: "100%",
    backgroundColor: "#3A3A3A",

    marginTop: -88,
  },
  clubIcon: {
    width: 100,
    aspectRatio: 1,
    borderRadius: 60,
    backgroundColor: COLORS.accentA,
    position: "absolute",
  },
  iconContainer: {
    alignItems: "center",
    justifyContent: "flex-end",
    height: "100%",
  },

  leaveText: {
    color: COLORS.textSecondary,
    justifyContent: "flex-end",
    alignItems: "flex-end",
    fontSize: 20,
    marginLeft: 20,
  },
  tabBarStyle: {
    backgroundColor: COLORS.surface,
  },
  memberListBackdrop: {
    marginHorizontal: 20,
    paddingTop: 20,
    borderRadius: 40,
    justifyContent: "center",
    flex: 1,
  },
  createButton: {
    width: 60,
    aspectRatio: 1,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surfaceAlternate,
    position: "absolute",
    bottom: 40,
    right: 40,
  },

  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContainer: {
    backgroundColor: COLORS.surface,
    padding: 5,
    borderRadius: 32,
    width: 350,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 24,
    color: COLORS.textPrimary,
    marginBottom: -10,
    marginTop: 0,
    fontFamily: "PoppinsBold",
    alignSelf: "center",
    textAlign: "center",
  },
  modalInputs: {
    paddingVertical: 10,
  },
  switchesContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  switchAndText: {
    flexDirection: "column",
  },
  menuOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    zIndex: 20,
    flexDirection: "row",
  },
  menuPanel: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    width: 280, // or whatever width your menu should be
    backgroundColor: COLORS.surface,
    zIndex: 30,
  },
  menuContainer: {
    width: 280,
    backgroundColor: COLORS.surface,
    padding: 20,
  },
  menuItem: {
    fontSize: 20,
    fontFamily: "PoppinsRegular",
    color: COLORS.textPrimary,
  },
  menuItemPressable: {
    alignItems: "center",
    flexDirection: "row",
    marginBottom: 8,
  },
  inputsContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
    padding: 20,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    gap: 12,
  },
  tagInputLabel: {
    color: "white",
    fontSize: 18,
    marginBottom: 4,
    fontWeight: "500",
    paddingHorizontal: 2,
  },
  tagInput: {
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: "#2a2a2a",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    fontSize: 16,
    color: "#fff",
  },
  tagInputContainer: {
    paddingHorizontal: 6,
    paddingVertical: 5,
  },
  tagSelection: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginVertical: 2,
    justifyContent: "center",
  },
  divider: {
    height: 2,
    backgroundColor: "#2a2a2a",
    width: "100%",
    marginVertical: 8,
  },
  placeHolder: {
    fontSize: 36,
    color: COLORS.textMuted,
    fontFamily: "PoppinsBold",
    alignSelf: "center",
  },
  addText: {
    color: COLORS.textPrimary,
    fontFamily: "PoppinsMedium",
    marginLeft: 20,
    fontSize: 16,
  },
  divSpace: {
    paddingVertical: 5,
    paddingHorizontal: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  divTitle: {
    fontSize: 28,
    color: COLORS.white,
    marginBottom: 0,
    marginTop: 0,
    fontFamily: "PoppinsMedium",
  },
  restrictedContainer: {
    flexDirection: "row",
    alignItems: "center",
    height: 70,
  },
  lockContainer: {
    width: 45,
    aspectRatio: 1,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surfaceThree,
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
  },
  restrictedText: {
    fontFamily: "PoppinsMedium",
    color: COLORS.textPrimary,
    marginLeft: 15,
    marginRight: 40,
    fontSize: 20,
  },
  infoPageText: {
    fontFamily: "NunitoRegular",
    fontSize: 18,
    color: COLORS.textPrimary,
    marginHorizontal: 10,
    marginVertical: 10,
  },
  infoSubheaderText: {
    fontFamily: "PoppinsSemiBold",
    fontSize: 28,
    color: COLORS.textPrimary,
    alignSelf: "center",
    marginHorizontal: 10,
  },
  infoPageAccent: {
    fontFamily: "NunitoMedium",
    fontSize: 24,
    color: COLORS.textPrimary,
    marginHorizontal: 10,
    marginVertical: 10,
  },
  infoIconContainer: {
    width: 45,
    aspectRatio: 1,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surfaceThree,
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    marginLeft: 15,
  },
  linkText: {
    fontFamily: "PoppinsMedium",
    fontSize: 18,
    color: "#1D4ED8",
    textDecorationLine: "underline",
    alignSelf: "center",
  },
  globalDesc: {
    marginVertical: 10,
    fontFamily: "LatoRegular",
    color: COLORS.textPrimary,
    marginHorizontal: 15,
    fontSize: 18,
    textAlign: "center",
  },
  globalOpt: {
    fontFamily: "PoppinsMedium",
    color: COLORS.textPrimary,
    marginHorizontal: 15,
    fontSize: 24,
  },
  buttonContainer: {
    flexDirection: "column",
  },
  innerButtonContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  buttonDiv: {
    height: 2,
    backgroundColor: COLORS.surface,
    marginVertical: 10,
    marginTop: 10,
    width: "90%",
  },
  buttonText: {
    fontFamily: "InterRegular",
    fontSize: 24,
    color: COLORS.textSecondary,
    paddingHorizontal: 20,
  },
});
