import { COLORS } from "@/constants/theme";
import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    backgroundColor: COLORS.background,
    flex: 1,
    alignItems: "center",
  },
  infoText: {
    fontSize: 20,
    color: COLORS.textPrimary,
    fontFamily: "PoppinsBold",
  },
  infoSubText: {
    fontFamily: "InterMedium",
    color: COLORS.textSecondary,
    fontSize: 14,
    marginTop: -6,
  },
  roleButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  roleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.white,
    paddingVertical: 16,
    paddingHorizontal: 7,
    borderRadius: 14,
    marginBottom: 20,
    width: 120,
    maxWidth: 300,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
    marginHorizontal: 6,
  },
  roleButtonText: {
    fontFamily: "PoppinsMedium",
    fontSize: 14,
    color: COLORS.surface,
  },
  roleDescription: {
    fontFamily: "PoppinsMedium",
    color: COLORS.textPrimary,
    fontSize: 20,
    textAlign: "center",
  },
  titleText: {
    fontFamily: "InterSemiBold",
    fontSize: 32,
    color: COLORS.textPrimary,
    alignSelf: "center",
  },
  header: {
    paddingTop: 0,
    paddingBottom: 10,
    paddingHorizontal: 20,

    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  headerTitle: {
    fontSize: 40,
    color: COLORS.white,
    marginBottom: 0,
    marginTop: 0,
    fontFamily: "PoppinsBold",
  },
  gradientBar: {
    height: 3,
    borderRadius: 2,
    width: "100%",
    marginBottom: 20,
  },
  userAvatar: {
    width: 60,
    aspectRatio: 1,
    borderRadius: 90,
    marginRight: 12,
    marginBottom: 5,
  },
  divider: {
    height: 2,
    backgroundColor: COLORS.textSecondary,
    marginVertical: 10,
    width: 300,
  },
  buttonContainer: {
    flexDirection: "column",
  },
  innerButtonContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  buttonDiv: {
    height: 2,
    backgroundColor: COLORS.surface,
    marginVertical: 10,
    marginTop: 10,
    width: "90%",
  },
  buttonText: {
    fontFamily: "InterRegular",
    fontSize: 24,
    color: COLORS.textSecondary,
    paddingHorizontal: 20,
  },
  subHeaderText: {
    fontFamily: "OpenSansRegular",
    fontSize: 20,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: -6,
  },
  subTitle: {
    fontFamily: "OpenSansRegular",
    fontSize: 18,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginTop: -8,
  },
  schoolName: {
    fontFamily: "PoppinsMedium",
    fontSize: 36,
    color: COLORS.textPrimary,
    textAlign: "center",
    marginHorizontal: 10,
  },
  joinCode: {
    fontFamily: "PoppinsMedium",
    fontSize: 22,
    color: COLORS.textPrimary,
    alignSelf: "center",
  },
  schoolTexts: {},
  schoolInfoText: {
    alignSelf: "center",
    color: COLORS.textSecondary,
    fontFamily: "InterMedium",
    fontSize: 20,
  },
  schoolInfoPart: {},
  dotIcon: {
    marginVertical: 10,
    color: COLORS.textMuted,
  },
  schoolDiv: {
    backgroundColor: COLORS.surfaceAlternate,
    width: "90%",
    height: 2,
    marginVertical: 3,
  },
  midHeaderText: {
    fontFamily: "PoppinsSemiBold",
    fontSize: 28,
    color: COLORS.textPrimary,
    alignSelf: "center",
    marginHorizontal: 10,
  },
  smallInfoText: {
    fontFamily: "PoppinsMedium",
    fontSize: 18,
    color: COLORS.textSecondary,
    alignSelf: "flex-start",
    marginLeft: 15,
  },
  picturesContainer: {
    flexDirection: "row",
    paddingLeft: 20,
    width: "100%",
    paddingVertical: 6,
  },
  smallUserAvatar: {
    width: 42,
    aspectRatio: 1,
    borderRadius: 50,
    marginRight: 12,
  },
  linkText: {
    fontFamily: "PoppinsMedium",
    fontSize: 18,
    color: "#1D4ED8",
    textDecorationLine: "underline",
    alignSelf: "center",
  },
  memberListBackdrop: {
    marginHorizontal: 20,
    paddingTop: 20,
    borderRadius: 40,
    justifyContent: "center",
    flex: 1,
  },
  divSpace: {
    paddingVertical: 5,
    paddingHorizontal: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  divTitle: {
    fontSize: 28,
    color: COLORS.white,
    marginBottom: 0,
    marginTop: 0,
    fontFamily: "PoppinsMedium",
  },
  clearText: {
    fontFamily: "InterRegular",
    fontSize: 18,
    color: COLORS.textPrimary,
    alignSelf: "center",
  },
  inputsContainer: {
    width: "100%",
    flex: 1,
    padding: 20,
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "stretch",
    gap: 12,
  },
  saveButton: {
    position: "absolute",
    left: 20,
    right: 20,
    borderRadius: 12,
    overflow: "hidden",
  },
  pressable: {
    backgroundColor: COLORS.publicGreen,
    paddingVertical: 14,
    alignItems: "center",
  },
  saveButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 16,
  },
});
